/**
 * data module, autogenerated by grunt. <br>
 * change and contribute to dictionary <br>
 *  <br>
 * for date extraction <br>
 *  <br>
 * @readonly
 * @module data/en/lexicon/dates
 */

declare var zip:any;
zip = { months: 
   { january: 1,
     february: 2,
     march: 3,
     april: 4,
     may: 5,
     june: 6,
     july: 7,
     august: 8,
     september: 9,
     october: 10,
     november: 11,
     december: 12,
     jan: 1,
     feb: 2,
     mar: 3,
     apr: 4,
     jun: 6,
     jul: 7,
     aug: 8,
     sep: 9,
     sept: 9,
     oct: 10,
     nov: 11,
     dec: 12 },
  monthsAbbrevs: 
   { jan: 1,
     feb: 2,
     mar: 3,
     apr: 4,
     jun: 6,
     jul: 7,
     aug: 8,
     sep: 9,
     sept: 9,
     oct: 10,
     nov: 11,
     dec: 12 },
  days: 
   { sunday: 0,
     monday: 1,
     tuesday: 2,
     wednesday: 3,
     thursday: 4,
     friday: 5,
     saturday: 6,
     sun: 0,
     mon: 1,
     tue: 2,
     wed: 3,
     thu: 4,
     fri: 5,
     sat: 6 },
  daysAbbrevs: { sun: 0, mon: 1, tue: 2, wed: 3, thu: 4, fri: 5, sat: 6 },
  dayS: '\\b(sunday|monday|tuesday|wednesday|thursday|friday|saturday|sun|mon|tue|wed|thu|fri|sat)',
  monthS: '(january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|sept|oct|nov|dec)' }
export = zip;