/**
 * data module, autogenerated by grunt. <br>
 * change and contribute to dictionary <br>
 *  <br>
 * adverbs to adjectives <br>
 *  <br>
 * @readonly
 * @module data/en/adverbs/decline
 */


  var zip:any = [ [ 'wholly', 'whole' ],
  [ 'idly', 'idle' ],
  [ 'fully', 'full' ],
  [ 'practically', 'practical' ],
  [ 'theoretically', 'theoretical' ],
  [ 'sporadically', 'sporadic' ],
  [ 'basically', 'basic' ],
  [ 'grammatically', 'grammatical' ],
  [ 'alphabetically', 'alphabetical' ],
  [ 'economically', 'economical' ],
  [ 'conically', 'conical' ],
  [ 'politically', 'political' ],
  [ 'vertically', 'vertical' ],
  [ 'critically', 'critical' ],
  [ 'fantastically', 'fantastic' ],
  [ 'mystically', 'mystical' ],
  [ 'pornographically', 'pornographic' ],
  [ 'jolly', 'jolly' ] ]

export = (function () {
				var o = {};
				zip.forEach(function(a) {
					o[a[0]] = a[1];
				});
				return o;
			})();