/**
 * data module, autogenerated by grunt. <br>
 * change and contribute to dictionary <br>
 *  <br>
 * singular nouns having irregular plurals <br>
 * and uncountable nouns <br>
 * {{.refs}} PRPs that can be a reference (e.g. "she"), <br>
 * {{.PRP}} all PRP "nouns",{{.PP}} all PP "nouns",{{.entityBlacklist}},{{.personBlacklist}} <br>
 *  <br>
 * @readonly
 * @module data/en/nouns/index
 */

declare var zip:any;
zip = { refs: [ 'you', 'he', 'she', 'it', 'they', 'him', 'her', 'them' ],
  PRP: 
   { i: true,
     you: true,
     he: true,
     she: true,
     it: true,
     we: true,
     they: true,
     me: true,
     him: true,
     her: true,
     us: true,
     them: true,
     thou: true,
     il: true,
     elle: true,
     '\'em': true },
  PP: 
   { mine: true,
     yours: true,
     his: true,
     her: true,
     hers: true,
     its: true,
     our: true,
     ours: true,
     theirs: true,
     their: true },
  ppRefs: 
   { mine: 'i',
     yours: 'you',
     his: 'he',
     her: 'she',
     hers: 'she',
     its: 'it',
     our: 'we',
     ours: 'we',
     theirs: 'they',
     their: 'they',
     them: 'they' },
  entityBlacklist: 
   { west: true,
     western: true,
     east: true,
     eastern: true,
     north: true,
     northern: true,
     south: true,
     southern: true,
     today: true,
     yesterday: true,
     tomorrow: true,
     era: true,
     century: true,
     my: true,
     your: true,
     itself: true,
     the: true,
     '&': true },
  personBlacklist: 
   [ 'center',
     'house',
     'park',
     'square',
     'centre',
     'memorial',
     'school',
     'bridge',
     'university',
     'college',
     'foundation',
     'institute',
     'club',
     'museum',
     'hall',
     'arena',
     'stadium',
     'partner',
     'the',
     'ave',
     'blvd',
     'uss',
     'ss',
     'for',
     'and',
     '&' ] }
export = zip;