/**
 * data module, autogenerated by grunt. <br>
 * change and contribute to dictionaryRules <br>
 *  <br>
 * regexes and functions for number parsing <br>
 *  <br>
 * @readonly
 * @module data/en/rules/number
 */
import d = require('../lexicon/numbers');
declare var zip:any;
zip = { negative: /^(-|minus|negative)[\s\-]/i,
  factors: 
   [ { reg: /\b(a)?(one-)?(\s)?half([\s\-])?(of\s)?/i, mult: 0.5 },
     { reg: /\b(a)?(one-)?(\s)?quarter([\s\-])?(of\s)?/i,
       mult: 0.25 } ],
  ordinals: /(?:\w*)(st|nd|rd|th)(?: |$)/i }
export = zip;