import _ = require("../../../nlp/_");

declare var zip:any;
zip = { male: 
   { will: '3m,&,ard,is,3ms',
     fred: ',e~ck,d&,~ck,dy',
     marc: 'us,,o,os,;',
     darr: ';l,yl,2,;,@',
     fran: 'k,cis,cisco,kl@,k&',
     terr: 'y,0ce,2ce,;l',
     rand: 'y,all,olph,al',
     brad: '1y,,ford,y',
     jeff: 'rey,,ery,ry',
     john: ',ny,n&,ath0',
     greg: 'ory,,g,o~o',
     mar: 'k,t@,v@,io,shall,ty,lon,l@',
     car: 'l,los,lton,roll,y,ey',
     ken: '!th,,t,ny,dall,d~ck',
     har: 'old,ry,vey,1y,#n,~son',
     ste: 'v2,ph2,ve,wart,ph0,rl@g',
     jer: 'ry,emy,ome,em3h,mai!,ald',
     mic: 'ha;,heal,ah,key,h;',
     dar: 'yl,@,!ll,w@,ius',
     dan: '&l,ny,,e',
     wil: 'bur,son,bert,fred,fredo',
     ric: 'hard,ky,ardo,k,key',
     cli: 'fford,nton,fton,nt,ff',
     cla: 'r2ce,ude,yton,rk,y',
     ben: 'jam@,,n&,ny,ito',
     rod: '!y,e~ck,olfo,ger,',
     rob: 'ert,erto,b&,',
     gar: 'y,ry,rett,#nd',
     sam: 'u;,,my,m&',
     and: 'rew,re,y,res',
     jos: 'eph,e,hua,h',
     joe: ',l,y,sph',
     leo: '_rd,n,,_rdo',
     tom: ',my,as,m&',
     bry: '0,0t,ce,on',
     ant: 'hony,onio,oi!,on',
     jac: 'k,ob,kson',
     cha: 'r1s,d,rl&,se',
     sha: 'wn,!,un',
     bre: 'nt,tt,nd0,t',
     jes: 'se,us,s',
     al: 'bert,0,1n,fred,ex0der,ex,v@,#n,fredo,berto,ej0dro,fonso,ton,,onzo,i,varo',
     ro: '_ld,ger,y,nn&,#nd,n,ss,osev;t,g;io,#ndo,m0,cky,yce,scoe,ry',
     de: 'nnis,rek,0,r~ck,lbert,v@,wey,xter,way!,met~us,nis,smond',
     ja: 'mes,son,y,red,v&r,ke,sper,mal,rrod',
     el: 'mer,lis,bert,3s,ijah,don,i,ton,liot,liott,v@,wood',
     ma: 'tthew,nu;,u~ce,thew,x,tt,lcolm,ck,son',
     do: '_ld,ug#s,n,nn&,ug,m@ic,y1,m@go,m@ick',
     er: 'ic,!st,ik,!sto,ick,v@,n&,w@',
     ra: 'ymond,lph,y,mon,fa;,ul,miro,pha;',
     ed: 'ward,w@,d&,gar,uardo,,mund,mond',
     co: 'rey,ry,dy,l@,n%d,r!lius',
     le: 'roy,wis,ster,#nd,vi',
     lo: 'uis,nn&,r2zo,r2,w;l,u&,u,g0',
     da: 'vid,1,ve,mon,l#s,mi0,m&n',
     jo: '_th0,n,rge,rd0,_thon,aqu@',
     ru: 'ss;l,b2,dolph,dy,fus,ss;,sty',
     ke: 'v@,ith,lv@,rmit',
     ar: 'thur,nold,m0do,turo,ch&,m0d',
     re: 'gi_ld,x,y_ldo,ub2,gg&',
     ge: 'orge,%ld,!,%rd,offrey,%rdo',
     la: 'rry,wr2ce,nce,ur2ce,mar,mont',
     mo: 'r~s,ses,nte,ises,nty',
     ju: '0,st@,lio,li0,lius,nior',
     pe: 'ter,dro,rry,te,rcy',
     tr: 'avis,oy,evor,2t',
     he: 'nry,rbert,rm0,ctor,ath',
     no: 'rm0,;,ah,#n,rbert',
     em: '0u;,il,ilio,mett,m0u;',
     wa: 'lter,y!,rr2,l#ce,de',
     mi: 'ke,gu;,lton,tch;l,1s',
     sa: 'lvador,lvatore,nt3go,ul,ntos',
     ch: '~stopher,~s,ester,~sti0,uck',
     pa: 'ul,t~ck,blo,t',
     st: '01y,uart,0',
     hu: 'gh,bert,go,mberto',
     br: 'i0,uce,0don,a@',
     vi: 'ctor,nc2t,rgil,c2te',
     ca: 'lv@,meron,1b',
     gu: 'y,il1rmo,stavo',
     lu: 'is,ther,ke,cas',
     gr: '0t,ady,over,aham',
     ne: 'il,lson,al,d',
     t: 'homas,imothy,odd,ony,heodore,im,y1r,ed,yro!,aylor,er2ce,immy,oby,eddy,yson',
     s: 'cott,e0,id!y,ergio,eth,p2cer,herm0,ylvester,imon,h;don,cotty,olomon',
     r: 'y0',
     n: 'icho#s,ath0,ath0&l,ick,ico#s',
     a: 'dam,aron,d~0,ust@,ng;o,b%ham,mos,b;,gust@,ugust,dolfo',
     b: 'illy,obby,arry,er_rd,ill,ob,yron,#ke,ert,oyd,ill&,#i!,art,uddy,urton',
     e: 'uge!,arl,verett,n~que,v0,ar!st,f%@,th0,steb0',
     h: 'oward,omer,o%ce,0s,al',
     p: 'hillip,hilip,reston,hil,&rre',
     c: '%ig,urtis,lyde,ecil,esar,ed~c,1ve#nd,urt',
     j: 'immy,im,imm&',
     g: '1nn,ordon,1n,ilbert,abr&l,ilberto',
     m: ';v@,yron,er1,ur%y',
     k: 'y1,arl,urt,irk,~stopher',
     o: 'scar,tis,liver,r#ndo,mar,w2,rvil1,tto',
     l: 'loyd,y1,io!l',
     f: 'loyd,er_ndo,;ix,;ipe,orrest,abi0,id;',
     w: 'es1y,2d;l,m,oodrow,@ston',
     d: 'ust@,ua!,way!,wight,rew,y#n',
     z: 'achary',
     v: 'ernon,0,0ce',
     i: '0,v0,saac,%,rv@g,sma;,g_cio,rv@',
     q: 'u2t@,u@ton',
     x: 'av&r' },
  female: 
   { mari: 'a,e,lyn,0,0!,_,ssa,b;,sa,sol,tza',
     kris: 't2,t@,ti_,ti,ti!,ty,ta,t&',
     jean: 'ette,!,!tte,n&,i!,ni!',
     chri: 'sti!,sti_,sty,st&,sta,sti',
     marg: 'aret,&,a~ta,ue~te,ret,o',
     ange: '#,lica,li_,l3,li!',
     fran: 'ces,ci!,cisca',
     kath: '12,e~!,y,ryn,a~!',
     sher: 'ry,~,yl,i,r&',
     caro: 'l,lyn,li!,1,li_',
     dian: 'e,a,!,_',
     jenn: 'ifer,&,y,a',
     luci: 'l1,a,nda,1',
     kell: 'y,i,ey,&',
     rosa: ',l&,l@d',
     jani: 'ce,e,s,!',
     stac: 'y,ey,&,i',
     shel: 'ly,1y,3',
     laur: 'a,2,&,;',
     trac: 'y,ey,i,&',
     jane: 't,,l1,tte',
     bett: 'y,&,e,ye',
     rose: 'mary,mar&,tta',
     joan: ',!,n,_',
     mar: 'y,tha,jor&,c3,1!,sha,y0n,c;#,ta,#,cy,ti_',
     lor: 'i,%i!,etta,a,e_,e!,_,&',
     sha: 'ron,nnon,~,w_,n_,_,u_',
     dor: 'othy,is,a,e2,thy,othea',
     cla: '%,ud3,ire,~ce,udette',
     eli: 'zabeth,sa,sabeth,se,za',
     kar: '2,#,a,i,@',
     tam: 'my,a%,i,m&,ika',
     ann: 'a,,e,&,ette',
     car: 'm2,r&,#,a,me#',
     mel: 'issa,0&,@da',
     ali: 'ce,c3,son,sha,sa',
     bri: 'tt0y,dget,tt!y,dgette',
     lyn: 'n,da,!,ette',
     del: 'ores,#,3,o~s',
     ter: 'esa,~,i',
     son: '3,ya,ja,d%',
     deb: 'o%h,%,b&,o%',
     jac: 'qu;i!,k&,qu;yn,lyn',
     lat: 'oya,asha,onya,isha',
     che: 'ryl,lsea,~,r&',
     vic: 'to~a,ki,k&,ky',
     sus: '0,&,0!,a_',
     rob: 'erta,yn',
     est: 'her,;1,;#,er',
     lea: 'h,,n!,nn',
     lil: 'li0,l&,a,y',
     ma: 'ure2,tt&,xi!,b;,e,d;i!,gg&,m&,b1,ndy,ude,y%,nue#,vis,gda1_,tilda',
     jo: 'yce,sephi!,,di,dy,h0_,sefi_,s&,c;yn,1!,ni,d&',
     be: 'verly,rtha,at~ce,rnice,th,ss&,cky,l@da,u#h,r_dette,th0y,tsy,at~z',
     ca: 'the~!,thy,ss0d%,ndace,ndice,mil1,itl@,ss&,th12,ll&',
     le: 'sl&,_,o_,tic3,igh,#,no%,o#,s1y,i#',
     el: 'ai!,1n,e0or,s&,#,e_,oise,vi%,sa,va,ma',
     sa: 'nd%,%h,%,lly,m0tha,b~_,ndy,d&,ll&',
     mi: 'ch;1,ldred,ch;e,nn&,~am,sty,ndy,%nda,ll&',
     co: 'nn&,l12,nst0ce,urt!y,%,~n!,nsu;o,r!l3',
     ju: 'l&,dith,dy,l3,0ita,a_,sti!',
     da: 'wn,n&l1,r1!,_,isy,r#,ph!',
     re: 'becca,!e,_,bekah,ba',
     al: 'ma,lison,berta,ex0d%,yssa,ta',
     ra: 'ch;,mo_,cha;,qu;,ch;1',
     an: 'drea,ita,a,g&,toi!tte,ton3',
     ge: '%ldi!,rtrude,org3,!v&ve,orgi_',
     de: 'nise,0_,siree,_,a_,e',
     ja: 'smi!,_,y!',
     lu: 'cy,z,#,pe,;#,isa',
     je: 'ssica,nifer,w;l,~',
     ad: 'a,r&n!,d&,;e,~a_,;i!',
     pa: 't~c3,me#,u#,uli!,tsy,m,tty,u1tte,tti,t~ce,t~ca,ige',
     ke: 'nd%,r~,isha,~',
     mo: 'nica,lly,nique,_,ll&',
     lo: 'uise,is,#',
     he: '1n,ather,idi,nr&tta,1!,1_',
     me: 'g0,rcedes,redith,gh0,ag0',
     wi: 'lma,l#,nn&',
     ga: 'il,y1,br&#,br&l1,1',
     er: '@,ica,ika,ma,!sti!',
     ce: 'cil3,l3,c;3,1ste,ci1',
     ka: 't&,y,t~_,y#,te',
     ol: 'ga,iv3,l&,a',
     li: 'nda,sa,ndsay,ndsey,zz&',
     na: 'ncy,tal&,omi,tasha,di!',
     la: 'ver!,_,don_,%',
     vi: 'rg@3,vi0,o#',
     ha: 'rr&t,n_h',
     pe: 'ggy,arl,nny,t%',
     br: '2da,0di,ooke',
     ki: 'mberly,m,mber1y,rst2',
     au: 'drey,tumn,d%',
     bo: 'nn&,bb&,nita,bbi',
     do: 'n_,lores,lly,m@ique',
     gl: 'o~a,adys,2da,2_',
     tr: 'ic3,i_,isha,udy',
     ta: '%,nya,sha,bitha',
     ro: 's&,x0!,ch;1,nda',
     am: 'y,0da,ber,;3',
     fa: 'ye,nn&,y',
     ni: 'co1,_,cho1,kki',
     ve: 'ronica,%,lma,r_',
     gr: 'ace,etch2,ac&#,ac&',
     b: 'arba%,#nca,arb%,i0ca',
     r: 'uth,ita,honda',
     s: 'hir1y,teph0&,ylv3,hei#,uz0!,ue,t;#,oph3,ilv3,oph&,tef0&,hee_,ummer,;ma,ocorro,ybil,imo!',
     c: 'ynth3,rystal,@dy,har1!,~sti_,1o',
     e: 'v;yn,mily,d_,dith,th;,mma,va,i12,unice,u#,ss&,ff&,tta,ug23',
     a: 'sh1y,p~l,g!s,r1!,imee,bigail,ida,bby,i12',
     t: 'heresa,i_,iff0y,h;ma,onya,oni,herese,on3',
     i: 're!,da,rma,sab;,!z,ng~d,va,moge!,sab;1',
     w: '0da,2dy,hit!y',
     p: 'hyllis,~scil#,olly',
     n: 'orma,;l&,o%,ett&,;l',
     f: 'lor2ce,;ic3,lo%,reda,ern,r&da',
     v: 'a1r&,a!ssa',
     j: 'ill,illi0',
     y: 'von!,o#nda,vette',
     g: 'i_,w2dolyn,w2,old&',
     l: 'yd3',
     m: 'yrt1,y%,ur&l,yr_',
     h: 'ilda',
     o: 'pal,%,f;3',
     k: 'rystal',
     d: 'ix&,i_',
     u: 'rsu#' },
  ambiguous: 
   [ 'casey',
     'jam&',
     '1e',
     'jaime',
     'jess&',
     'morg0',
     're!',
     'rob@',
     'devon',
     'kerry',
     'a1xis',
     'guadalupe',
     'b#ir',
     'kasey',
     'je0',
     'ma~on',
     'aubrey',
     'sh;by',
     'j0',
     'shea',
     'jade',
     'k2yatta',
     'k;sey',
     'shay',
     '#shawn',
     't~nity',
     'reg0',
     'jamm&',
     'cassidy',
     'chey2!',
     'reag0',
     'shiloh',
     'marlo',
     '0d%',
     'dev0',
     'rosa~o',
     '1e' ] }

export = (function () {
    var replN = function(w) {
      return _.repl(w, ['ie', 'na', 'la', 'ri', 'ne', 'ra', 'el', 'in', 'an', 'le', 'en', 'ia'])
    }
    // convert it to an easier format
    var o = {};
    ['male', 'female'].forEach(function(type) {
      for (var k in zip[type]) {
        var arr = replN(zip[type][k]).split(',');
        arr.forEach(function(w, i) {
          o[k + w] = type.charAt(0);
        })
      }
    });
    var ambi:any = zip.ambiguous.map(replN).reduce(function(h,s){ h[s]='a'; return h; }, o);
    zip.ambiguous = ambi;
    return o;
  })();